[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core/" }
cxx.workspace = true

[build-dependencies]
cxx-build.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]
